### PR TITLE
My proposal for #1 Support for string tables

### PR DESCRIPTION
**Pull request by scriptease**

### CODE REVIEW

**Comment by igorkulman** [comment]
Thanks for the PR. The functionality looks good, but I have some issues with the UX. It took me a while to figure out how to switch the string tables, I did not notice the new menu item appearing.

I would prefer something like this, I think it is more visible and usable

screen shot 2018-07-11 at 12 15 13

**Comment by scriptease** [comment]
bildschirmfoto 2018-07-15 um 13 43 20

**Comment by igorkulman** [comment]
Thanks, looks good!

**Comment by scriptease** [comment]
Thanks! 👍

Just a small thing the pin_alert_title in your localization should be "Deine PIN" in German :-)

**Pull request merged**
